###
GET http://localhost:3000/api/karyawan?

###
GET http://localhost:3000/api/karyawan/1

###
POST http://localhost:3000/api/karyawan
Content-Type: application/json

{
    "fullname": "superadmin",
    "username": "superadmin",
    "password": "superadmin"
}

###
PUT http://localhost:3000/api/karyawan/1
Content-Type: application/json

{
    "fullname": "superadmin1",
    "username": "superadmin1",
    "password": "superadmin1"
}

###
DELETE  http://localhost:3000/api/karyawan/1